org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[1,)

## Mod properties
mod_id=sporeadd
mod_name=SporeAdds
mod_license=All Rights Reserved
mod_version=2.2.1
mod_group_id=com.sporeadds.sporeaddsmod
mod_authors=rodmlgkiller
mod_description=A mod that allows the player to play as a spore infected miniboss or choose 4 diferent survivor classes with different skills to fight the infection. Each class is a strong gamechanger originally balanced for pvp so have that in account.
