modLoader="javafml"
loaderVersion="[47,)"              # Cambia según el rango requerido para tu versión de Forge
license="All Rights Reserved"

[[mods]]
modId="sporeadd"
version="${mod_version}"          # Cambia por la versión real de tu mod
displayName="Spore Add"
description="""
A mod that allows the player to play as a spore infected miniboss or choose 4 diferent survivor classes with different skills to fight the infection. Each class is a strong gamechanger originally balanced for pvp so have that in account.
"""
authors="rodmlgkiller"
mixins = "sporeadd.mixins.json"

[[dependencies.sporeadd]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.sporeadd]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.sporeadd]]
modId="origins"
mandatory=false
versionRange="[1.10.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.sporeadd]]
modId="pehkui"
mandatory=true
versionRange="[3.8.2,)"
ordering="NONE"
side="BOTH"